apiVersion: v1
kind: Secret
metadata:
  name: loki-promtail
  namespace: monitoring
type: Opaque
data:
  promtail.yaml: c2VydmVyOgogIGh0dHBfbGlzdGVuX3BvcnQ6IDkwODAKICBncnBjX2xpc3Rlbl9wb3J0OiAwCgpwb3NpdGlvbnM6CiAgZmlsZW5hbWU6IC9ydW4vcHJvbXRhaWwvcG9zaXRpb25zLnlhbWwKCmNsaWVudHM6CiAgLSB1cmw6IGh0dHA6Ly9sb2tpLm1vbml0b3Jpbmcuc3ZjLmNsdXN0ZXIubG9jYWw6MzEwMC9sb2tpL2FwaS92MS9wdXNoCgpzY3JhcGVfY29uZmlnczoKICAtIGpvYl9uYW1lOiBzeXN0ZW0KICAgIHN0YXRpY19jb25maWdzOgogICAgICAtIHRhcmdldHM6CiAgICAgICAgICAtIGxvY2FsaG9zdAogICAgICAgIGxhYmVsczoKICAgICAgICAgIGpvYjogdmFybG9ncwogICAgICAgICAgX19wYXRoX186IC92YXIvbG9nLypsb2c=