replicaCount: 1

loki:
  auth_enabled: false
  commonConfig:
    replication_factor: 1
  storage:
    type: filesystem
    filesystem:
      directory: /var/loki/chunks

persistence:
  enabled: true
  accessModes:
    - ReadWriteOnce
  size: 10Gi
  storageClassName: "" # Set to your storage class if needed

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

service:
  type: ClusterIP
  port: 3100

ingress:
  enabled: false

# If you want to deploy promtail as well, set enabled to true
promtail:
  enabled: false