replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: stable

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# Portul containerului (folosit de Deployment)
containerPort: 80

service:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - nginx.local
  tls:
    - secretName: nginx-tls
      hosts:
        - nginx.local

