replicaCount: 2

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: stable

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}


containerPort: 80

service:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80    
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443
      protocol: TCP

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - nginx.local
  tls:
    - secretName: nginx-tls
      hosts:
        - nginx.local

