replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: stable

serviceAccount:
  create: true
  name: ""

podAnnotations: {}

podSecurityContext: {}
securityContext: {}

resources: {}
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

nodeSelector: {}
tolerations: []
affinity: {}

# Nu defini liste separate de containerPorts (ar putea duce la dubluri).
# Majoritatea chart-urilor Nginx își extrag containerPort din service.targetPort (așteaptă numere).
# Dacă chart-ul tău cere explicit containerPort, folosește o singură valoare numerică:
containerPort: 80

service:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 80    # numeric — important (nu "http")
      protocol: TCP
    - name: https
      port: 443
      targetPort: 443   # numeric
      protocol: TCP

ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - nginx.local
  tls:
    - secretName: nginx-tls
      hosts:
        - nginx.local

