ingress:
  enabled: true
  ingressClassName: nginx
  hosts:
    - nginx.local
  tls:
    - secretName: nginx-tls
      hosts:
        - nginx.local

service:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
      name: http
    - port: 443
      targetPort: 443
      name: https
