apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-server-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""   # important să fie gol, ca PVC-ul să se lege
  hostPath:
    path: /mnt/data/prometheus-server