apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-alertmanager-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""   # la fel, trebuie gol
  hostPath:
    path: /mnt/data/prometheus-alertmanager