# pv-alertmanager.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-alertmanager
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: "/mnt/data/alertmanager"