apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: example
  namespace: default
spec:
  refreshInterval: "1m"
  secretStoreRef:
    name: secretstore-sample
    kind: SecretStore
  target:
    name: my-secret
    creationPolicy: Owner
  data:
    - secretKey: my-key
      remoteRef:
        key: my-vault-secret
