apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: secretstore-sample
  namespace: default
spec:
  provider:
    vault:
      server: "http://vault.default.svc.cluster.local:8200"
      path: "secret/data"
      version: "v2"
      auth:
        token:
          secretRef:
            name: vault-token
            key: token
